sudo: false
language: node_js
node_js:
  - node
  - lts/*
branches:
  except:
  - master
cache:
  directories:
#  - node_modules
  - ~/.npm
  - .jest
before_install:
  - npm update
install:
  - npm install jest
  - npm install
script:
  - npm ci
# - npx jest --ci
  - npm test
# - npm run coveralls