sudo: false
language: node_js
node_js:
  - "12.11.1"
#  - lts/*
branches:
  except:
  - master
cache:
  directories:
    - ~/.npm
before_script:
  - npm install -g npm@latest
script:
  - npm ci
  - npx jest --ci

# cache:
#   directories:
#   - node_modules
#   - ~/.npm
#   - .jest
# before_install:
#   - npm update
# install:
#   - npm install jest
#   - npm install -g npx
#   - npm install
# script:
#   - npm ci
#   - npm test --noStackTrace
